name: Demo pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag psi-app-demo:latest

    # - name: Run Flake8
    #   run: flake8 main.py --max-line-length=200
  test:
    needs: build
    steps:
    - name: Run tests
      run: |
        docker run psi-app-demo:latest pytest tests/test.py --verbose
  # deploy:
  #   needs: test
  #   steps:
  #   - name: Deploy to Heroku
  #     uses: akhileshns/heroku-deploy@v3.12.12
  #     with:
  #       heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #       heroku_app_name: "my-app-name"
  #       heroku_email: "
