name: Demo pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag psi-app-demo:latest
        docker save psi-app-demo:latest > /tmp/psi-app-demo.tgz
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: psi-app-demo
        path: /tmp/psi-app-demo.tgz

    # - name: Run Flake8
    #   run: flake8 main.py --max-line-length=200
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: psi-app-demo
        path: /tmp
    - name: Run tests
      run: |
        docker load --input /tmp/psi-app-demo.tgz
        docker run psi-app-demo:latest pytest tests/test.py --verbose
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name : Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: 'psi-app-demo-300'
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: psi-app-demo
        path: /tmp
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/919687749794/locations/global/workloadIdentityPools/github-actions/providers/github'
        service_account: psi-app-demo@psi-app-demo-300.iam.gserviceaccount.com
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: psi-app-demo
        source: /tmp/psi-app-demo.tgz
  